version: '3.8'

services:
  redis:
    image: 'redis:alpine'
    container_name: social_commerce_redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  localstack:
    image: localstack/localstack:latest
    container_name: social_commerce_localstack
    environment:
      - SERVICES=sqs
      - DEBUG=1
      - LOCALSTACK_HOST=localstack
    ports:
      - '4566:4566'
    volumes:
      - ./localstack-init:/etc/localstack/init/ready.d
      - '/var/run/docker.sock:/var/run/docker.sock'

volumes:
  redis_data:
